# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:16:56+00:00

from __future__ import annotations

from enum import Enum


class Format(Enum):
    json = 'json'
    xml = 'xml'


class Action(Enum):
    APPROVE = 'APPROVE'
    REJECT = 'REJECT'
    REJECT_BLACKLIST = 'REJECT_BLACKLIST'
